WorkshopApp/Models/Enrollment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WorkshopApp.Models
{
    public class Enrollment
    {

        public int Id { get; set; }

        [Display(Name ="Студенти")]

        public int StudentId { get; set; }
        [Display(Name = "Студенти")]
        public Student Student { get; set; }

        [Display(Name = "Предмети")]

        public int CourseId { get; set; }
        [Display(Name = "Предмети")]


        public Course Course { get; set; }


        [Display(Name = "Семестар")]

        public String Semester { get; set; }

        [Display(Name = "Година")]
        public int? Year { get; set; }


        [Display(Name = "Оценка")]
        public int Grade { get; set; }

        [Display(Name ="Семинарска")]

        public string SeminalUrl { get; set; }

        [Display(Name ="Проект")]

        public String ProjectUrl { get; set; }

        [Display(Name = "Поени од испит")]

        public int ExamPoints { get; set; }

        [Display(Name = "Поени од семинарски")]

        public int SeminalPoints { get; set; }

        [Display(Name = "Поени од проекти")]

        public int ProjectPoints { get; set; }

        [Display(Name = "Дополнителни поени")]

        public int AdditionalPoints { get; set; }

        [Display(Name = "Дата на положување")]
        [DataType(DataType.Date)]
        public DateTime FinishDate { get; set; }



    }
}

WorkshopApp/Controllers/EnrollmentsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WorkshopApp.Areas.Identity.Data;
using WorkshopApp.Data;
using WorkshopApp.Models;
using WorkshopApp.ViewModels;

namespace WorkshopApp.Controllers
{
    public class EnrollmentsController : Controller
    {
        private readonly WorkshopAppContext _context;
        private readonly IHostingEnvironment webHostingEnvironment;
        private readonly UserManager<WorkshopAppUser> userManager;

        public EnrollmentsController(WorkshopAppContext context, IHostingEnvironment hostingEnvironment, UserManager<WorkshopAppUser> userMgr)
        {
            _context = context;
            webHostingEnvironment = hostingEnvironment;
            userManager = userMgr;
        }

        // GET: Enrollments
    
        public async Task<IActionResult> Index(string SearchIndex, string SearchTitle, string SearchSemester, int? SearchYear)
        {
            IQueryable<Enrollment> enrollments = _context.Enrollment;
            if (!string.IsNullOrEmpty(SearchIndex))
            {
                enrollments = enrollments.Where(s => s.Student.StudentId.Contains(SearchIndex));
            }

            if (!string.IsNullOrEmpty(SearchTitle))
            {
                enrollments = enrollments.Where(c => c.Course.Title.Contains(SearchTitle));
            }

            IQueryable<string> semesters = enrollments.OrderBy(m => m.Semester).Select(m => m.Semester).Distinct();
            IQueryable<int?> years = enrollments.OrderBy(m => m.Year).Select(m => m.Year).Distinct();

            if (SearchYear != null)
            {
                enrollments = enrollments.Where(e => e.Year == SearchYear);
            }

            if (!string.IsNullOrEmpty(SearchSemester))
            {
                enrollments = enrollments.Where(e => e.Semester == SearchSemester);
            }

            enrollments = enrollments.Include(e => e.Student).Include(e => e.Course);

            var viewmodel = new EnrollmentFilterViewModel
            {
                Enrollments = await enrollments.ToListAsync(),
                Years = new SelectList(await years.ToListAsync()),
                Semesters = new SelectList(await semesters.ToListAsync())
            };

            
            return View(viewmodel);
          }


        // GET: Enrollments/Details/5
     
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollment
                .Include(e => e.Course)
                .Include(e => e.Student)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (enrollment == null)
            {
                return NotFound();
            }

            return View(enrollment);
        }

        // GET: Enrollments/Create
     
        public IActionResult Create()
        {
            ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Id");
            ViewData["StudentId"] = new SelectList(_context.Student, "Id", "Id");
            return View();
        }

        // POST: Enrollments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
  
        public async Task<IActionResult> Create([Bind("Id,StudentId,CourseId,Semester,Year,Grade,SeminalUrl,ProjectUrl,ExamPoints,SeminalPoints,ProjectPoints,AdditionalPoints,FinishDate")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(enrollment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Id", enrollment.CourseId);
            ViewData["StudentId"] = new SelectList(_context.Student, "Id", "Id", enrollment.StudentId);
            return View(enrollment);
        }

        // GET: Enrollments/Edit/5
     
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollment.FindAsync(id);
            if (enrollment == null)
            {
                return NotFound();
            }
            ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Id", enrollment.CourseId);
            ViewData["StudentId"] = new SelectList(_context.Student, "Id", "Id", enrollment.StudentId);
            return View(enrollment);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
     
        public async Task<IActionResult> Edit(int id, [Bind("Id,StudentId,CourseId,Semester,Year,Grade,SeminalUrl,ProjectUrl,ExamPoints,SeminalPoints,ProjectPoints,AdditionalPoints,FinishDate")] Enrollment enrollment)
        {
            if (id != enrollment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(enrollment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EnrollmentExists(enrollment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CourseId"] = new SelectList(_context.Course, "Id", "Id", enrollment.CourseId);
            ViewData["StudentId"] = new SelectList(_context.Student, "Id", "Id", enrollment.StudentId);
            return View(enrollment);
        }

        // GET: Enrollments/Delete/5
     
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollment
                .Include(e => e.Course)
                .Include(e => e.Student)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (enrollment == null)
            {
                return NotFound();
            }

            return View(enrollment);
        }

        // POST: Enrollments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
    
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var enrollment = await _context.Enrollment.FindAsync(id);
            _context.Enrollment.Remove(enrollment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }



        //GET: Enrollents/CreateEnrollment

        /* public IActionResult CreateEnrollment()
         {
             ViewData["courseID"] = new SelectList(_context.Course, "Id", "Title");
             ViewData["studentID"] = new SelectList(_context.Student, "Id", "FullName");
             return View();
         }

         //POST: Enrollments/CreateEnrollment

         [HttpPost]
         [ValidateAntiForgeryToken]
         public async Task<IActionResult> CreateEnrollment([Bind("Id,CourseId,StudentId,Semester,Year")] Enrollment enrollment)
         {
             if (ModelState.IsValid)
             {
                 _context.Add(enrollment);
                 await _context.SaveChangesAsync();
                 return RedirectToAction(nameof(Index));
             }
             ViewData["courseID"] = new SelectList(_context.Course, "Id", "Title", enrollment.CourseId);
             ViewData["studentID"] = new SelectList(_context.Student, "Id", "FullName", enrollment.StudentId);
             return View(enrollment);
         }*/

        // GET: Enrollments/StudentEdit/5
        [Authorize(Roles = "Student")]
        public async Task<IActionResult> StudentEdit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollment.FindAsync(id);
            if (enrollment == null)
            {
                return NotFound();
            }
            ViewData["courseID"] = new SelectList(_context.Course, "Id", "Title", enrollment.CourseId);
            ViewData["studentID"] = new SelectList(_context.Student, "Id", "FullName", enrollment.StudentId);
            return View(enrollment);
        }

        // POST: Enrollments/StudentEdit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Student")]
        public async Task<IActionResult> StudentEdit(int id, IFormFile pUrl, [Bind("Id,CourseId,StudentId,Semester,Year,Grade,SeminalUrl,ProjectUrl,ExamPoints,SeminalPoints,ProjectPoints,AdditionalPoints,FinishDate")] Enrollment enrollment)
        {
            if (id != enrollment.Id)
            {
                return NotFound();
            }

            EnrollmentsController uploadUrl = new EnrollmentsController(_context, webHostingEnvironment,userManager);
            enrollment.SeminalUrl = uploadUrl.UploadedFile(pUrl);


            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(enrollment);

WorkshopApp/Views/Enrollments/Create.cshtml
@model WorkshopApp.Models.Enrollment

@{
    ViewData["Title"] = "Create";
}

<h1>Додади студент</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StudentId" class="control-label"></label>
                <select asp-for="StudentId" class ="form-control" asp-items="ViewBag.StudentId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CourseId" class="control-label"></label>
                <select asp-for="CourseId" class ="form-control" asp-items="ViewBag.CourseId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Semester" class="control-label"></label>
                <input asp-for="Semester" class="form-control" />
                <span asp-validation-for="Semester" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Grade" class="control-label"></label>
                <input asp-for="Grade" class="form-control" />
                <span asp-validation-for="Grade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeminalUrl" class="control-label"></label>
                <input asp-for="SeminalUrl" class="form-control" />
                <span asp-validation-for="SeminalUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectUrl" class="control-label"></label>
                <input asp-for="ProjectUrl" class="form-control" />
                <span asp-validation-for="ProjectUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExamPoints" class="control-label"></label>
                <input asp-for="ExamPoints" class="form-control" />
                <span asp-validation-for="ExamPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeminalPoints" class="control-label"></label>
                <input asp-for="SeminalPoints" class="form-control" />
                <span asp-validation-for="SeminalPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectPoints" class="control-label"></label>
                <input asp-for="ProjectPoints" class="form-control" />
                <span asp-validation-for="ProjectPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdditionalPoints" class="control-label"></label>
                <input asp-for="AdditionalPoints" class="form-control" />
                <span asp-validation-for="AdditionalPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FinishDate" class="control-label"></label>
                <input asp-for="FinishDate" class="form-control" />
                <span asp-validation-for="FinishDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Додади" class="btn btn-secondary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад кон листата</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WorkshopApp/Views/Enrollments/CreateEnrollment.cshtml
@model WorkshopApp.Models.Enrollment

@{ ViewData["Title"] = "Запиши студент"; }

<h1>Запиши студент</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CourseId" class="control-label"></label>
                <select asp-for="CourseId" class="form-control" asp-items="ViewBag.courseID"></select>
            </div>
            <div class="form-group">
                <label asp-for="StudentId" class="control-label"></label>
                <select asp-for="StudentId" class="form-control" asp-items="ViewBag.studentID"></select>
            </div>
            <div class="form-group">
                <label asp-for="Semester" class="control-label"></label>
                <input asp-for="Semester" class="form-control" />
                <span asp-validation-for="Semester" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Enrollments">Назад кон листата</a>
</div>

WorkshopApp/Views/Enrollments/Delete.cshtml
@model WorkshopApp.Models.Enrollment

@{
    ViewData["Title"] = "Delete";
}

<h1>Избриши</h1>

<h3>Дали сте сигурни?</h3>
<div>
  
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Student.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Course.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Semester)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Grade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Grade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SeminalUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SeminalUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExamPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExamPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SeminalPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SeminalPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AdditionalPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AdditionalPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FinishDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FinishDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Избриши" class="btn btn-danger" /> |
        <a asp-action="Index">Назад кон листата</a>
    </form>
</div>

WorkshopApp/Views/Enrollments/Details.cshtml
@model WorkshopApp.Models.Enrollment

@{
    ViewData["Title"] = "Details";
}

<h1>Детали</h1>

<div>
   
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Student.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Course)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Course.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Semester)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Grade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Grade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SeminalUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SeminalUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExamPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExamPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SeminalPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SeminalPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AdditionalPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AdditionalPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FinishDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FinishDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Промени</a> |
    <a asp-action="Index">Назад кон листата</a>
</div>

WorkshopApp/Views/Enrollments/Edit.cshtml
@model WorkshopApp.Models.Enrollment

@{
    ViewData["Title"] = "Edit";
}

<h1>Промени</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="StudentId" class="control-label"></label>
                <select asp-for="StudentId" class="form-control" asp-items="ViewBag.StudentId"></select>
                <span asp-validation-for="StudentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CourseId" class="control-label"></label>
                <select asp-for="CourseId" class="form-control" asp-items="ViewBag.CourseId"></select>
                <span asp-validation-for="CourseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Semester" class="control-label"></label>
                <input asp-for="Semester" class="form-control" />
                <span asp-validation-for="Semester" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Grade" class="control-label"></label>
                <input asp-for="Grade" class="form-control" />
                <span asp-validation-for="Grade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeminalUrl" class="control-label"></label>
                <input asp-for="SeminalUrl" class="form-control" />
                <span asp-validation-for="SeminalUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectUrl" class="control-label"></label>
                <input asp-for="ProjectUrl" class="form-control" />
                <span asp-validation-for="ProjectUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExamPoints" class="control-label"></label>
                <input asp-for="ExamPoints" class="form-control" />
                <span asp-validation-for="ExamPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeminalPoints" class="control-label"></label>
                <input asp-for="SeminalPoints" class="form-control" />
                <span asp-validation-for="SeminalPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectPoints" class="control-label"></label>
                <input asp-for="ProjectPoints" class="form-control" />
                <span asp-validation-for="ProjectPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdditionalPoints" class="control-label"></label>
                <input asp-for="AdditionalPoints" class="form-control" />
                <span asp-validation-for="AdditionalPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FinishDate" class="control-label"></label>
                <input asp-for="FinishDate" class="form-control" />
                <span asp-validation-for="FinishDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Зачувај" class="btn btn-secondary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад кон листата</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WorkshopApp/Views/Enrollments/Index.cshtml
@model WorkshopApp.ViewModels.EnrollmentFilterViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Запишани студенти</h1>
<hr />

<form asp-action="Index" method="get">
    Индекс: <input type="text" asp-for="SearchIndex" />
    Наслов на предмет: <input type="text" asp-for="SearchTitle" />
    Година: <select asp-for="SearchYear" asp-items="Model.Years">
        <option value=""></option>
    </select>
    Семестар: <select asp-for="SearchSemester" asp-items="Model.Semesters">
        <option value=""></option>
    </select>
    <input type="submit" value="Филтер" />
</form>
<hr />
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Students[0].StudentId)
            </th>
            <th>
                Студенти
            </th>
            <th>
                Предмети
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Courses[0].Semester)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Enrollments[0].Grade)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.Enrollments[0].FinishDate)
            </th>


            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Enrollments)
        {
        <tr>
            <td nowrap="nowrap">
                @Html.DisplayFor(modelItem => item.Student.StudentId)
            </td>
            <td nowrap="nowrap">
                @Html.DisplayFor(modelItem => item.Student.FullName)
            </td>
            <td nowrap="nowrap">
                @Html.DisplayFor(modelItem => item.Course.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Semester)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FinishDate)
            </td>
            <td nowrap="nowrap">
                <a asp-action="Edit" asp-route-id="@item.Id">Промени</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Детали</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Избриши</a>
            </td>
        </tr>
        }
    </tbody>
</table>
<hr />
<span><a asp-action="StudentEnrollment">Запиши студенти</a>  |  <a asp-action="StudentUnEnrollment">Отпиши студенти</a></span>