WorkshopApp/Models/Teacher.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WorkshopApp.Models
{
    public class Teacher
    {
        public int Id { get; set; }

        [Display(Name = "Име")]
        public string FirstName { get; set; }

        [Display(Name = "Презиме")]
        public string LastName { get; set; }

        [Display(Name = "Степен")]
        public string Degree { get; set; }

        [Display(Name = "Звање")]
        public string AcademicRank { get; set; }

        [Display(Name = "Канцеларија")]
        public string OfficeNumber { get; set; }

        [Display(Name = "Дата на вработување")]
        [DataType(DataType.Date)]
        public DateTime HireDate { get; set; }

        [Display(Name = "Слика на профил")]
        public string? profilePicture { get; set; }

        [Display(Name = "Име и Презиме")]
        public string FullName
        {
            get
            {
                return FirstName + " " + LastName;
               

            }
        }

        [InverseProperty("FirstTeacher")]
        [Display(Name ="Предмети")]
        public ICollection<Course> FirstCourses { get; set; }


        [InverseProperty("SecondTeacher")]

        public ICollection<Course> SecondCourses { get; set; }





    }
}

WorkshopApp/ViewModels/TeacherCourses.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WorkshopApp.Models;

namespace WorkshopApp.ViewModels
{
    public class TeacherCourses
    {

        public Teacher Teacher { get; set; }
        public Course Course { get; set; }
        public IList<Enrollment> Enrollments { get; set; }
        public string SInd { get; set; }
        public SelectList Semesters { get; set; }
        public string SSem { get; set; }
        public SelectList Years { get; set; }
        public int SYear { get; set; }
    }
}

WorkshopApp/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WorkshopApp.Areas.Identity.Data;
using WorkshopApp.Data;
using WorkshopApp.Models;
using WorkshopApp.ViewModels;

namespace WorkshopApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TeachersController : Controller
    {
        private readonly WorkshopAppContext _context;
        private readonly IHostingEnvironment webHostEnvironment;
        private readonly UserManager<WorkshopAppUser> userManager;

        public TeachersController(WorkshopAppContext context, IHostingEnvironment hostingEnviroment, UserManager<WorkshopAppUser> userMgr)
        {
            _context = context;
            webHostEnvironment = hostingEnviroment;
            userManager = userMgr;
        }

        // GET: Teachers
       
        public async Task<IActionResult> Index(string SearchFullName, string SearchRank, string SearchDegree)
        {
            IEnumerable<Teacher> teachers = _context.Teacher.AsEnumerable();
            IQueryable<string> rankQuery = _context.Teacher.OrderBy(t => t.AcademicRank).Select(t => t.AcademicRank).Distinct();
            IQueryable<string> degreeQuery = _context.Teacher.OrderBy(c => c.Degree).Select(g => g.Degree).Distinct();

            if (!string.IsNullOrEmpty(SearchFullName))
            {
                teachers = teachers.Where(t => t.FullName.Contains(SearchFullName));
            }

            if (!string.IsNullOrEmpty(SearchRank))
            {
                teachers = teachers.Where(s => s.AcademicRank == SearchRank);
            }

            if (!string.IsNullOrEmpty(SearchDegree))
            {
                teachers = teachers.Where(s => s.Degree.Contains(SearchDegree));
            }

            var viewmodel = new TeacherFilterViewModel
            {
                Teachers = teachers.ToList(),
                Ranks = new SelectList(await rankQuery.ToListAsync()),
                Degrees = new SelectList(await degreeQuery.ToListAsync())


            };

            return View(viewmodel);
        }


        // GET: Teachers/Details/5
      
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // GET: Teachers/Create
     
        public IActionResult Create()
        {
            return View();
        }

        // POST: Teachers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
      
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Degree,AcademicRank,OfficeNumber,HireDate")] Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                _context.Add(teacher);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(teacher);
        }

        // GET: Teachers/Edit/5
   
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher.FindAsync(id);
            if (teacher == null)
            {
                return NotFound();
            }
            return View(teacher);
        }

        // POST: Teachers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public async Task<IActionResult> Edit(int id, IFormFile imageUrl, [Bind("Id,FirstName,LastName,Degree,AcademicRank,OfficeNumber,HireDate,profilePicture")] Teacher teacher)
        {
            if (id != teacher.Id)
            {
                return NotFound();
            }

            TeachersController uploadImage = new TeachersController(_context, webHostEnvironment,userManager);
            teacher.profilePicture = uploadImage.UploadedFile(imageUrl);

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(teacher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeacherExists(teacher.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", new { id = teacher.Id });
            }
            return View(teacher);
        }

        // GET: Teachers/Delete/5
      
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // POST: Teachers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
       
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var teacher = await _context.Teacher.FindAsync(id);
            _context.Teacher.Remove(teacher);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

       
        public string UploadedFile(IFormFile file)
        {
            string uniqueFileName = null;
            if (file != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "teacherimages");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(file.FileName);
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }
       
        private bool TeacherExists(int id)
        {
            return _context.Teacher.Any(e => e.Id == id);
        }

     
        public async Task<IActionResult> EnrollmentsCourse(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .Include(c => c.FirstTeacher)
                .Include(c => c.SecondTeacher)
                .Include(c => c.Students)
                .ThenInclude(e => e.Student)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.Id == id);

            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

    
        public async Task<IActionResult> Teachercourses(int? id, string SearchTitle, string CourseSemester, string CourseProgram)
        {
            IQueryable<Course> courses = _context.Course.AsQueryable();
            IQueryable<int> semesterQuery = _context.Course.OrderBy(c => c.Semester).Select(m => m.Semester).Distinct();
            IQueryable<string> programQuery = _context.Course.OrderBy(c => c.Programme).Select(g => g.Programme).Distinct();

            if (!string.IsNullOrEmpty(SearchTitle))
            {
                courses = courses.Where(t => t.Title.Contains(SearchTitle));
            }

            if (!string.IsNullOrEmpty(CourseProgram))
            {
                courses = courses.Where(s => s.Programme == CourseProgram);
            }

            if (!string.IsNullOrEmpty(CourseSemester))
            {
                courses = courses.Where(s => s.Semester.ToString().Equals(CourseSemester));
            }

            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teacher
                .Include(c => c.FirstCourses)
                  .Include(d => d.SecondCourses)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teacher == null)
            {
                return NotFound();
            }


            CourseFilterViewModel viewmodel = new CourseFilterViewModel
            {
                Teacher = teacher,
                Courses = await courses.ToListAsync(),
                ProgramList = new SelectList(await programQuery.ToListAsync()),
                SemesterList = new SelectList(await semesterQuery.ToListAsync())
            };
            //return View(teacher);
            return View(viewmodel);
        }


    }

}

WorkshopApp/Views/Teachers/Create.cshtml
@model WorkshopApp.Models.Teacher

@{
    ViewData["Title"] = "Create";
}

<h1>Креирај</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Degree" class="control-label"></label>
                <input asp-for="Degree" class="form-control" />
                <span asp-validation-for="Degree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AcademicRank" class="control-label"></label>
                <input asp-for="AcademicRank" class="form-control" />
                <span asp-validation-for="AcademicRank" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeNumber" class="control-label"></label>
                <input asp-for="OfficeNumber" class="form-control" />
                <span asp-validation-for="OfficeNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HireDate" class="control-label"></label>
                <input asp-for="HireDate" class="form-control" />
                <span asp-validation-for="HireDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Додади" class="btn btn-secondary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад кон листата</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WorkshopApp/Views/Teachers/Delete.cshtml
@model WorkshopApp.Models.Teacher

@{
    ViewData["Title"] = "Delete";
}

<h1>Избриши</h1>

<h3>Дали сте сигурни?</h3>
<div>
    <h4>Teacher</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Degree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Degree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AcademicRank)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AcademicRank)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OfficeNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OfficeNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HireDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HireDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Избриши" class="btn btn-danger" /> |
        <a asp-action="Index">Назад кон листата</a>
    </form>
</div>

WorkshopApp/Views/Teachers/Details.cshtml
@model WorkshopApp.Models.Teacher

@{
    ViewData["Title"] = "Details";
    var photoPath = "~/teacherimages/" + (Model.profilePicture ?? "Noimage.webp");
}

<h1>Детали</h1>

<div>

    <hr />
    <img src="@photoPath"
         height="200" width="200"
         asp-append-version="true" />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Degree)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Degree)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AcademicRank)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AcademicRank)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OfficeNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OfficeNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.HireDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.HireDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Промени</a> |
    <a asp-action="Index">Назад кон листата</a>
</div>

WorkshopApp/Views/Teachers/Edit.cshtml
@model WorkshopApp.Models.Teacher

@{
    ViewData["Title"] = "Edit";
}

<h1>Промени</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Degree" class="control-label"></label>
                <input asp-for="Degree" class="form-control" />
                <span asp-validation-for="Degree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AcademicRank" class="control-label"></label>
                <input asp-for="AcademicRank" class="form-control" />
                <span asp-validation-for="AcademicRank" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficeNumber" class="control-label"></label>
                <input asp-for="OfficeNumber" class="form-control" />
                <span asp-validation-for="OfficeNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HireDate" class="control-label"></label>
                <input asp-for="HireDate" class="form-control" />
                <span asp-validation-for="HireDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                @if (Model.profilePicture == null)
                {
                    <label class="control-label">Слика:</label>
                    <input type="file" name="imageUrl" /> }
                else
                {
                    <label>Избрана слика:</label>
                    <img src="~/teacherimages/@Model.profilePicture"
                         height="100" width="100"
                         asp-append-version="true" />
                    <br />
                    <input type="file" name="imageUrl" />}
            </div>
            <div class="form-group">
                <input type="submit" value="Зачувај" class="btn btn-secondary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад кон листата</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WorkshopApp/Views/Teachers/Index.cshtml
@model WorkshopApp.ViewModels.TeacherFilterViewModel

@{
    ViewData["Title"] = "Index";
}

<style>
    td,th{
        width:auto;
    }
</style>

<h1>Професори</h1>

<p>
    <a asp-action="Create">Додади професор</a>
</p>

<form asp-controller="Teachers" asp-action="Index" method="get">
    <p>
        Име и презиме: <input type="text" asp-for="SearchFullName" />
        Академски ранг: <select asp-for="SearchRank" asp-items="Model.Ranks">
            <option value="">Сите</option>
        </select>
        Степен на образование: <select asp-for="SearchDegree" asp-items="Model.Degrees">

            <option value="">Сите</option>
        </select>
        <input type="submit" value="Филтер" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <td></td>
            <th>
                @Html.DisplayNameFor(model => model.Teachers[0].FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Teachers[0].LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Teachers[0].Degree)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Teachers[0].AcademicRank)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Teachers[0].OfficeNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Teachers[0].HireDate)
            </th>
           
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Teachers) {
        <tr>
            <td> <a asp-controller="Admin" asp-action="TeacherView" asp-route-id="@item.Id">Регистрирај</a> </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Degree)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AcademicRank)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OfficeNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HireDate)
            </td>

            <td>
                <a  asp-action="Teachercourses" asp-route-id="@item.Id">Прeдмети</a> |
                <a asp-action="Edit" asp-route-id="@item.Id">Промени</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Детали</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Избриши</a>
            </td>
        </tr>
}
    </tbody>
</table>

WorkshopApp/Views/Teachers/Teachercourses.cshtml
@model WorkshopApp.ViewModels.CourseFilterViewModel

@{ ViewData["Title"] = "Index"; }


<h1>Проф. @Model.Teacher.FullName</h1>
<h4>Предмети</h4>

<dd class="col-sm-10">
    <table class="table">
        <tr>
            <th>Наслов</th>
            <th>Кредити</th>
            <th>Семестар</th>
            <th>Програма</th>
            <th>Ниво</th>

        </tr>
        @if (Model.Teacher.FirstCourses != null)
        {
            foreach (var item in Model.Teacher.FirstCourses)
            {

<tr>
    <td nowrap="nowrap">
        @Html.DisplayFor(modelItem => item.Title)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Credits)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Semester)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Programme)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.EducationLevel)
    </td>

    <td nowrap="nowrap">
        <a asp-controller="Courses" asp-action="EnrollmentsCourse" asp-route-id="@item.Id">Студенти</a> |
        <a asp-controller="Courses" asp-action="Edit" asp-route-id="@item.Id">Промени</a> |
        <a asp-controller="Courses" asp-action="Details" asp-route-id="@item.Id">Детали</a> |
        <a asp-controller="Courses" asp-action="Delete" asp-route-id="@item.Id">Избриши</a>
    </td>
</tr>}
            }

        @if (Model.Teacher.SecondCourses != null)
        {
            foreach (var item in Model.Teacher.SecondCourses)
            {
<tr>
    <td nowrap="nowrap">
        @Html.DisplayFor(modelItem => item.Title)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Credits)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Semester)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Programme)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.EducationLevel)
    </td>

    <td nowrap="nowrap">
        <a asp-controller="Courses" asp-action="EnrollmentsCourse" asp-route-id="@item.Id">Студенти</a> |
        <a asp-controller="Courses" asp-action="Edit" asp-route-id="@item.Id">Промени</a> |
        <a asp-controller="Courses" asp-action="Details" asp-route-id="@item.Id">Детали</a> |
        <a asp-controller="Courses" asp-action="Delete" asp-route-id="@item.Id">Избриши</a>
    </td>
</tr>}
            }
    </table>
</dd>
<div>

    <a asp-action="Index">Назад кон листата</a>
</div>